version: '2.3'

services:
  frontend:
    container_name: prod-abstraction-landing-page-fe
    image: abstraction-landing-page-fe:latest
    restart: unless-stopped
    command: sh -c "yarn build && yarn start"
    ports:
      - "6789:5000"
    volumes:
      - ..:/app/
      - fe_node_modules:/app/node_modules
    env_file:
      - production.env
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    
volumes:
  fe_node_modules:
