import { Poppins, Bakbak_One, Noto_Sans } from 'next/font/google'
import "/public/assets/css/style.css"
import "/public/assets/css/responsive.css"

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: "--poppins",
  display: 'swap',
})
const notosans = Noto_Sans({
  weight: ['700'],
  subsets: ['latin'],
  variable: "--notosans",
  display: 'swap',
})

export const metadata = {
  title: 'Binabox | NFT Portfolio Next.js Template',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={`${poppins.variable} ${notosans.variable} body header-fixed`}>{children}</body>
      </html>
  )
}
// --poppins: var(--poppins);
// --bakbak: var(--bakbak)
